apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: znt64rzvi-python 
  janus-idp.io/tekton: znt64rzvi-python
  backstage.io/kubernetes-id: znt64rzvi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: znt64rzvi-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  